version: '2'
services:
  rest3:
    build: .
    image: apprenda/rest3
    ports:
      - "5000:5000"
    links:
      - rest3api
    restart: always
  rest3api:
    build: .
    image: dutronlabs/rest3api
    ports:
      - "8080:8080"
    links:
      - redis
    restart: always
  redis:
    image: redis
    volumes:
      - /opt/redis:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    restart: always