version: '2'
services:
  rest3-ui:
    image: ielab/rest3-ui
    ports:
      - "5000:5000"
    links:
      - rest3-api
    restart: always
  rest3-api:
    image: ielab/rest3-api
    ports:
      - "5001:5001"
    links:
      - redis
    restart: always
  redis:
    image: redis
    volumes:
      - /opt/redis:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    restart: always